// 日本旅遊 2026/06 - 行程資料
window.TRIP_DATA = {
  meta: {
    title: "東京六日",
    subtitle: "Tokyo · Six Days · Early Summer",
    dateRange: "2026.06.13 — 06.18",
    travelers: 2,
    hotel: {
      name: "ELE Hotel Higashi Ueno",
      address: "東京都台東區東上野",
      checkIn: "6/13 20:30",
      checkOut: "6/18 10:00",
      lat: 35.7125777,
      lng: 139.784355,
    },
    flights: {
      out: { code: "JX804", from: "桃園 T1", to: "成田 T2", dep: "15:00", arr: "19:25", date: "6/13", duration: "3h 25m", aircraft: "Airbus A321NEO" },
      back: { code: "JX801", from: "成田 T2", to: "桃園 T1", dep: "14:10", arr: "16:50", date: "6/18", duration: "3h 40m" },
    },
    budget: {
      currency: "JPY",
      rate: 0.21, // 1 JPY ≈ 0.21 TWD (estimate)
      categories: [
        { key: "flight",    label: "機票",     amount: 28000, twd: true },
        { key: "hotel",     label: "住宿 5晚", amount: 75000 },
        { key: "transport", label: "交通",     amount: 18000 },
        { key: "food",      label: "餐飲",     amount: 60000 },
        { key: "shopping",  label: "購物",     amount: 80000 },
        { key: "tickets",   label: "門票",     amount: 12000 },
      ],
    },
    weather: [
      { date: "6/13", icon: "☀️", high: 27, low: 19, cond: "晴" },
      { date: "6/14", icon: "⛅", high: 26, low: 20, cond: "多雲" },
      { date: "6/15", icon: "🌧", high: 24, low: 19, cond: "陣雨" },
      { date: "6/16", icon: "☀️", high: 28, low: 20, cond: "晴" },
      { date: "6/17", icon: "⛅", high: 27, low: 21, cond: "多雲" },
      { date: "6/18", icon: "☀️", high: 28, low: 22, cond: "晴" },
    ],
    packing: {
      essentials: ["護照（效期>6個月）", "日幣現金", "Suica 卡", "網卡 / WiFi 機", "行動電源（手提）", "信用卡"],
      clothing: ["短袖 6-7 件", "長袖薄外套 2 件", "長褲 / 短褲", "舒適好走的鞋", "雨傘 / 折傘", "帽子 / 太陽眼鏡"],
      toiletries: ["盥洗包", "防曬乳", "保養品（<100ml）", "個人藥品", "口罩"],
      gadgets: ["相機 + 充電器", "手機充電線", "轉接頭（日本A型）", "耳機"],
      paperwork: ["登機證", "飯店訂房證明", "保險文件", "緊急聯絡清單"],
    },
    emergency: [
      { label: "台北駐日經濟文化代表處", phone: "+81-3-3280-7811" },
      { label: "日本警察", phone: "110" },
      { label: "日本救護", phone: "119" },
    ],
  },

  days: [
    // ── DAY 1 ─────────────────────────────────────
    {
      id: "d1",
      idx: 1,
      date: "6/13",
      weekday: "六",
      title: "出發日",
      subtitle: "桃園 → 東京",
      kanji: "出発",
      headline: "雲端之上，向東京前進",
      areas: ["桃園機場", "成田機場", "上野"],
      heroNote: "STARLUX JX804 · 飛行 3h 25m · 抵達後直奔上野",
      events: [
        { time: "12:00", emoji: "🚖", type: "transit", title: "前往桃園機場第一航廈", note: "建議出發前 3 小時抵達" },
        { time: "15:00", emoji: "✈️", type: "flight", title: "STARLUX JX804 起飛", note: "Airbus A321NEO · 飛行 3h 25m", lat: 25.0797, lng: 121.2342 },
        { time: "19:25", emoji: "🛬", type: "flight", title: "抵達成田國際機場 T2", lat: 35.7720, lng: 140.3929,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJXehfC2oL3IARS6FkiKgYBqo" },
        { time: "19:45", emoji: "🎫", type: "transit", title: "Skyliner 售票中心購票", note: "Skyliner 特急｜上野直達 41 分鐘｜¥2,520/人" },
        { time: "20:30", emoji: "🏨", type: "hotel", title: "辦理入住 ELE Hotel Higashi Ueno", lat: 35.7125777, lng: 139.784355,
          mapsUrl: "https://www.google.com/maps/place/?q=35.7125777,139.784355" },
      ],
      meals: [
        { slot: "晚餐", name: "屯京拉麵 本店", type: "濃厚拉麵", rating: "4.0", url: "https://www.google.com/maps/place/?q=place_id:ChIJTf7VQ2iNGGAR4NgYdVc3Bcg" },
        { slot: "晚餐", name: "無敵家", type: "超濃豚骨", rating: "4.2", url: "https://www.google.com/maps/place/?q=place_id:ChIJd_kIJ2iNGGARzbI-17Azk4I" },
        { slot: "晚餐", name: "Ramen 鴨 to 蔥 上野", type: "鴨高湯拉麵", rating: "超人氣", url: "https://www.google.com/maps/place/?q=35.707355,139.785021" },
      ],
      tips: [
        "出發前確認護照、日幣、Suica、網卡",
        "成田至上野建議搭 Skyliner（比 JR 快、舒適）",
        "行動電源放手提行李（不可托運！）",
      ],
      photoSpot: "成田機場 STARLUX 登機門 · 上野阿美橫夜景",
      pullQuote: "旅程的開始，是在登機口聽到自己護照被翻動的聲音。",
    },

    // ── DAY 2 ─────────────────────────────────────
    {
      id: "d2",
      idx: 2,
      date: "6/14",
      weekday: "日",
      title: "東京車站・秋葉原・上野",
      subtitle: "丸之內 → 秋葉原 → 阿美橫",
      kanji: "電気街",
      headline: "從紅磚車站走進電器街的霓虹",
      areas: ["丸之內", "秋葉原", "上野"],
      heroNote: "海鮮迴轉壽司 → 寶可夢中心 → 電器街掃貨 → 阿美橫",
      events: [
        { time: "09:30", emoji: "🚉", type: "place", title: "東京車站", note: "JR 各線匯集點", lat: 35.6812, lng: 139.7671,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJC3Cf2PuLGGAROGFmSPykFKM" },
        { time: "10:00", emoji: "🍣", type: "food", title: "迴轉壽司 根室花丸 KITTE", note: "北海道直送 · 不接受訂位 · ⭐ 4.1", lat: 35.6798, lng: 139.7644,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJuzydSvqLGGARXTqdIJs_08Y" },
        { time: "11:30", emoji: "🎮", type: "shop", title: "寶可夢中心 東京DX", note: "高島屋 T&T 13F · 旗艦店", lat: 35.6794, lng: 139.7686,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJvVMBnf2LGGARQhgCY-LZMCQ" },
        { time: "13:30", emoji: "⚡", type: "place", title: "秋葉原電器街", lat: 35.6989, lng: 139.7731,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJzdWdgh2MGGARh4kg2pVZL3c" },
        { time: "14:00", emoji: "🕹️", type: "shop", title: "秋葉原逛街 (3 hr)", note: "Yodobashi · アニメイト · ラジオ会館 · Surugaya / Book Off" },
        { time: "17:30", emoji: "🛍️", type: "shop", title: "上野阿美橫商店街", note: "藥妝 · 零食 · 生鮮 · ⭐ 4.3 · 關門 20:00", lat: 35.7080, lng: 139.7747,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJh7eDrwCPGGARCs9fpCkKS2U" },
      ],
      meals: [
        { slot: "午餐", name: "根室花丸 KITTE", type: "迴轉壽司", rating: "4.1", url: "https://www.google.com/maps/place/?q=place_id:ChIJuzydSvqLGGARXTqdIJs_08Y" },
        { slot: "晚餐", name: "炸豬排山家 上野", type: "炸豬排 高CP", rating: "—", url: "https://www.google.com/maps/place/?q=35.707399,139.783437" },
        { slot: "晚餐", name: "焼肉陽山道 上野本店", type: "燒肉 在地老店", rating: "—", url: "https://www.google.com/maps/place/?q=35.7072,139.7839" },
        { slot: "晚餐", name: "Ramen 鴨 to 蔥 上野", type: "鴨高湯拉麵", rating: "超人氣", url: "https://www.google.com/maps/place/?q=35.707355,139.785021" },
      ],
      tips: [
        "根室花丸不開放訂位，建議 10:00 開店前就到",
        "秋葉原預估 3-4 小時；阿美橫約 1.5 小時",
        "寶可夢中心人多，限購注意",
      ],
      photoSpot: "東京車站紅磚正面 · 秋葉原十字路口霓虹",
      pullQuote: "霓虹下的廣告聲、扭蛋落地的清脆，是電器街的呼吸。",
    },

    // ── DAY 3 ─────────────────────────────────────
    {
      id: "d3",
      idx: 3,
      date: "6/15",
      weekday: "一",
      title: "東京鐵塔・新宿・池袋",
      subtitle: "Tokyo Tower → Shinjuku → Ikebukuro",
      kanji: "鉄塔",
      headline: "從紅色鐵骨到摩天百貨",
      areas: ["芝公園", "新宿", "池袋"],
      heroNote: "150m 展望台 → 新宿伊勢丹 → 池袋 Sunshine City",
      events: [
        { time: "09:30", emoji: "🗼", type: "place", title: "東京鐵塔", note: "主展望台 ¥1,200 · 頂上 ¥1,800 · ⭐ 4.5", lat: 35.6586, lng: 139.7454,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJCewJkL2LGGAR3Qmk0vCTGkg" },
        { time: "13:00", emoji: "🏙️", type: "place", title: "新宿車站", lat: 35.6895, lng: 139.7005,
          mapsUrl: "https://www.google.com/maps/place/?q=35.6895,139.7005" },
        { time: "13:30", emoji: "🛍️", type: "shop", title: "新宿逛街 (3.5 hr)", note: "伊勢丹 · 三丁目商店街 · 小田急 / 京王 B1 美食 · OIOI" },
        { time: "17:30", emoji: "🚉", type: "place", title: "池袋車站", lat: 35.7295, lng: 139.7109,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJJ1xYpaCSGGARumLc8TmsILQ" },
        { time: "18:00", emoji: "🛍️", type: "shop", title: "池袋逛街 (2.5 hr)", note: "東池袋 PARCO · Sunshine City · 西池袋 LOFT" },
      ],
      meals: [
        { slot: "午餐", name: "六歌仙 新宿西口", type: "和牛燒肉吃到飽", rating: "🏆 第一", url: "https://www.google.com/maps/place/?q=35.6898,139.6936" },
        { slot: "午餐", name: "Gyu Tongue Lemon", type: "牛舌名店", rating: "新宿必吃", url: "https://www.google.com/maps/place/?q=35.689722,139.700556" },
        { slot: "晚餐", name: "屯京拉麵 本店", type: "拉麵", rating: "4.0", url: "https://www.google.com/maps/place/?q=place_id:ChIJTf7VQ2iNGGAR4NgYdVc3Bcg" },
        { slot: "晚餐", name: "無敵家", type: "超濃豚骨", rating: "4.2", url: "https://www.google.com/maps/place/?q=place_id:ChIJd_kIJ2iNGGARzbI-17Azk4I" },
        { slot: "晚餐", name: "鳥貴族 新宿", type: "平價串燒", rating: "居酒屋", url: "https://www.google.com/maps/place/?q=35.689487,139.702042" },
        { slot: "晚餐", name: "USHIGORO 新宿三丁目", type: "頂級和牛燒肉", rating: "需訂位 ⚠️", url: "https://www.google.com/maps/place/?q=35.691,139.7037" },
      ],
      tips: [
        "東京鐵塔建議 9:30 前抵達，避免人潮",
        "六歌仙吃到飽附中文菜單，網路訂位較保險",
        "USHIGORO 需要提前至少 1 週訂位",
      ],
      photoSpot: "東京鐵塔下方仰拍 · 新宿西口夜景",
      pullQuote: "鐵塔的紅，是這座城市寫給天空的明信片。",
    },

    // ── DAY 4 ─────────────────────────────────────
    {
      id: "d4",
      idx: 4,
      date: "6/16",
      weekday: "二",
      title: "明治神宮・原宿・澀谷",
      subtitle: "Meiji → Harajuku → Shibuya",
      kanji: "神宮",
      headline: "從神社參道走進世界最忙路口",
      areas: ["明治神宮", "表參道", "澀谷"],
      heroNote: "9:00 神宮 → 表參道 → 澀谷 Scramble → 任天堂東京",
      events: [
        { time: "09:00", emoji: "⛩️", type: "place", title: "明治神宮", note: "免費入場 · ⭐ 4.6 · 參道散步 15 分鐘", lat: 35.6764, lng: 139.6993,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ5SZMmreMGGARcz8QSTiJyo8" },
        { time: "10:30", emoji: "🛍️", type: "shop", title: "表參道 / 原宿竹下通", note: "精品街 + 可麗餅 + 復古服飾", lat: 35.6658, lng: 139.7127,
          mapsUrl: "https://www.google.com/maps/place/?q=35.6658,139.7127" },
        { time: "13:00", emoji: "🚦", type: "place", title: "澀谷交叉路口", note: "世界最繁忙路口 · ⭐ 4.5 · Starbucks 2F 可俯瞰", lat: 35.6595, lng: 139.7004,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJK9EM68qLGGARacmu4KJj5SA" },
        { time: "14:00", emoji: "🛍️", type: "shop", title: "澀谷逛街 (2.5 hr)", note: "SHIBUYA 109 · Hikarie · LOFT / HMV" },
        { time: "16:30", emoji: "🎮", type: "shop", title: "任天堂 東京旗艦店", note: "PARCO 6F · 10:00–21:00 · 假日排隊 · ⭐ 4.5", lat: 35.6614, lng: 139.6972,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ7Su1FK6NGGARAr7UK5NjmMo" },
      ],
      meals: [
        { slot: "午餐", name: "十方鮨 澀谷", type: "板前壽司 omakase", rating: "Threads 推薦", url: "https://www.google.com/maps/place/?q=35.659,139.7014" },
        { slot: "午餐", name: "松榮 惠比壽", type: "平價 omakase", rating: "近站", url: "https://www.google.com/maps/place/?q=35.6465,139.7131" },
        { slot: "晚餐", name: "USHIGORO 銀座", type: "A5 黑毛和牛", rating: "🏆 百名店", url: "https://www.google.com/maps/place/?q=35.6758,139.7701" },
        { slot: "晚餐", name: "壽司郎 有樂町", type: "平價迴轉壽司", rating: "交通方便", url: "https://www.google.com/maps/place/?q=35.675069,139.774017" },
      ],
      tips: [
        "明治神宮石子路較多，穿舒適好走的鞋",
        "任天堂 PARCO 店建議非假日去",
        "澀谷 Sky 需要事先網路訂票",
      ],
      photoSpot: "明治神宮鳥居 · 澀谷 Scramble 高處",
      pullQuote: "穿過鳥居的那一刻，東京突然安靜了下來。",
    },

    // ── DAY 5 ─────────────────────────────────────
    {
      id: "d5",
      idx: 5,
      date: "6/17",
      weekday: "三",
      title: "淺草寺・晴空塔",
      subtitle: "Asakusa → Tokyo Skytree",
      kanji: "雷門",
      headline: "從江戶古寺仰望平成新塔",
      areas: ["淺草", "押上"],
      heroNote: "8:30 雷門 → 仲見世 → 花月堂菠蘿麵包 → 晴空塔 350m",
      events: [
        { time: "08:30", emoji: "⛩️", type: "place", title: "淺草寺", note: "雷門 → 仲見世 → 本殿 · ⭐ 4.5 · 全日開放", lat: 35.7148, lng: 139.7967,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ8T1GpMGOGGARDYGSgpooDWw" },
        { time: "09:30", emoji: "🛍️", type: "shop", title: "仲見世通", note: "人形燒 · 雷神堂 · 傳統工藝品" },
        { time: "10:30", emoji: "🥐", type: "food", title: "淺草 花月堂", note: "現烤巨大菠蘿麵包 · 排隊名物", lat: 35.712056, lng: 139.796799,
          mapsUrl: "https://www.google.com/maps/place/?q=35.712056,139.796799" },
        { time: "13:00", emoji: "🗼", type: "place", title: "東京晴空塔", note: "TEMBO DECK 350m ¥2,100 · GALLERIA 450m +¥1,000 · ⭐ 4.4", lat: 35.7101, lng: 139.8107,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ35ov0dCOGGARKvdDH7NPHX0" },
        { time: "14:00", emoji: "🛍️", type: "shop", title: "SOLAMACHI 商場", note: "4F 周邊店 · B2 Tower Yard 土產 · 關 21:00" },
      ],
      meals: [
        { slot: "早午餐", name: "一蘭 淺草店", type: "拉麵", rating: "4.3", url: "https://www.google.com/maps/place/?q=place_id:ChIJ7_4BvsaOGGAR3ulL0uSzNpc" },
        { slot: "早午餐", name: "並木藪蕎麥", type: "蕎麥麵 (1913)", rating: "Tabelog 3.74", url: "https://www.google.com/maps/place/?q=35.7115,139.7971" },
        { slot: "早午餐", name: "尾張屋 淺草", type: "炸蝦天婦羅蕎麥", rating: "🏆 160 年", url: "https://www.google.com/maps/place/?q=35.715,139.7945" },
        { slot: "午餐", name: "天婦羅 大黑家 本店", type: "天婦羅丼", rating: "3.5", url: "https://www.google.com/maps/place/?q=place_id:ChIJ79EaJsGOGGARHgsoZXYMZO0" },
        { slot: "下午茶", name: "淺草炸肉餅", type: "街邊小吃", rating: "必吃", url: "https://www.google.com/maps/place/?q=35.712345,139.796655" },
        { slot: "晚餐", name: "六厘舎 晴空塔店", type: "沾麵", rating: "東京代表", url: "https://www.google.com/maps/place/?q=35.7101,139.8107" },
        { slot: "晚餐", name: "藏壽司 淺草ROX", type: "迴轉壽司", rating: "—", url: "https://www.google.com/maps/place/?q=35.714765,139.796655" },
      ],
      tips: [
        "淺草寺早去早享受，10 點後人潮爆炸",
        "晴空塔票可在官網預購，避免排隊",
        "淺草寺周邊夜景很美，可考慮晚上再逛一次",
      ],
      photoSpot: "雷門大燈籠 · 晴空塔玻璃地板",
      pullQuote: "在 350 公尺高的玻璃前，江戶的屋瓦像一張展開的地圖。",
    },

    // ── DAY 6 ─────────────────────────────────────
    {
      id: "d6",
      idx: 6,
      date: "6/18",
      weekday: "四",
      title: "返程日",
      subtitle: "東京 → 桃園",
      kanji: "帰国",
      headline: "把整座城市裝進行李",
      areas: ["上野", "成田"],
      heroNote: "STARLUX JX801 · 14:10 起飛 · 飛行 3h 40m",
      events: [
        { time: "08:00", emoji: "🛍️", type: "shop", title: "阿美橫最後採買", note: "藥妝補貨 · 零食土產", lat: 35.7080, lng: 139.7747,
          mapsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJh7eDrwCPGGARCs9fpCkKS2U" },
        { time: "10:00", emoji: "🏨", type: "hotel", title: "ELE Hotel 退房 + 存放行李", lat: 35.7125777, lng: 139.784355 },
        { time: "10:30", emoji: "🚄", type: "transit", title: "上野搭 Skyliner ⬅️ 最晚！", note: "車程 41 分鐘 · 11:11 抵達 T2" },
        { time: "11:30", emoji: "✈️", type: "flight", title: "成田 T2 Check-in / 托運", note: "預留 12:30 完成安檢" },
        { time: "14:10", emoji: "✈️", type: "flight", title: "JX801 起飛", lat: 35.7720, lng: 140.3929 },
        { time: "16:50", emoji: "🛬", type: "flight", title: "桃園 T1 抵達", lat: 25.0797, lng: 121.2342 },
      ],
      meals: [
        { slot: "午餐", name: "上野藪蕎麥", type: "明治 25 年百年老舖", rating: "—", url: "https://www.google.com/maps/place/?q=35.7099,139.7746" },
        { slot: "午餐", name: "Nadai Unatoto 上野", type: "平價鰻魚飯", rating: "—", url: "https://www.google.com/maps/place/?q=35.7075,139.7831" },
      ],
      tips: [
        "Suica 餘額退款（機場可辦）",
        "確認沒有液體超過 100ml",
        "搭 Skyliner 前往成田（上野出發 41 分鐘）",
      ],
      photoSpot: "成田機場登機門 · 機翼上的雲海",
      pullQuote: "回程時，行李變重了，心也是。",
      checklist: [
        "整理所有行李，確認沒有遺漏",
        "飯店退房（11:00 前）",
        "Suica 餘額退款",
        "確認護照和所有證件",
        "最後採購土產",
        "確認液體未超過 100ml",
        "搭 Skyliner 前往成田",
      ],
    },
  ],
};
